---
- hosts: master
  become: yes
  become_method: sudo
  gather_facts: no
  remote_user: vagrant

  tasks: 

  - name: "[Task 1] generation join token pour joindre les workers"
    command: kubeadm token create --print-join-command
    register: join_command

  - name: "[Task 2] copy join token command"
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

# on all workers

- hosts: workers
  become: yes
  become_method: sudo
  gather_facts: no
  remote_user: vagrant

  tasks:

  - name: Copy the join command to server location
    copy: 
      src: join-command
      dest: /tmp/join-command.sh 
      mode: 0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh
